### PR TITLE
Prevent `from * import *` to be splitted

### PR DESCRIPTION
**Pull request by adhikasp**
This will prevent a `from something import a, b, c`  to be splitted.

Test code 
```python
from math import sqrt, log, tan, cos
import os, sys, collections

print(log(2))
print(tan(5))
print(os)
print(sys)
```

Result
```diff
--- original/tes.py
+++ fixed/tes.py
@@ -1,5 +1,6 @@
-from math import sqrt, log, tan, cos
-import os, sys, collections
+from math import log, tan
+import os
+import sys

 print(log(2))
 print(tan(5))
```

Closes https://github.com/myint/autoflake/issues/7

### CODE REVIEW

**Comment by myint** [comment]
Cool! I'll take a closer look later this week.

**Comment by myint** [comment]
I committed a relevant test case in 71fa850254280805c0007c78b35f4fd41f35e579. Could you try that?

Also, could you add the following test case?

```python
from frommy import abc, frommy, xyz
```

Currently, with this pull requests, I get the following error from the above.

```
$ ./autoflake.py foo.py
Traceback (most recent call last):
  File "./autoflake.py", line 595, in <module>
    sys.exit(main())
  File "./autoflake.py", line 589, in main
    standard_error=sys.stderr)
  File "./autoflake.py", line 572, in _main
    fix_file(name, args=args, standard_out=standard_out)
  File "./autoflake.py", line 462, in fix_file
    remove_unused_variables=args.remove_unused_variables)
  File "./autoflake.py", line 441, in fix_code
    remove_unused_variables=remove_unused_variables))))
TypeError: sequence item 0: expected str instance, NoneType found
```

Thanks

**Comment by adhikasp** [comment]
Ok will do it 👍

**Comment by adhikasp** [comment]
Updated:
- More robust regex to only call my new function if `from` is on the start of line.
- The bug you post is because my function completely remove the file content on first pass (hence the next iteration in `fix_code` got `None`, not a string). I fix this by return `pass` in case of `from something import unused1, unused2` and rely on removing useless pass routine to clean up.
- Additional test cases

**Comment by myint** [comment]
How about:

```python
from collections import defaultdict, namedtuple as xyz
```

It seems to currently give:

```
$ ./autoflake.py foo.py
--- original/foo.py
+++ fixed/foo.py
@@ -1 +1 @@
-from collections import defaultdict, namedtuple as xyz
+from collections import as, namedtuple, xyz
```

**Comment by adhikasp** [comment]
`from ... import ... as` handled correctly.

One thing that still buggy is if the input have irregular spacing (more than 1) will not removed because i directly compare them with output from `pyflakes`.
```python 
from a import b   as   c 
```

Do you think we should handle that too?

**Comment by myint** [comment]
Great work!

I think leaving irregular spacing untouched is fine.

I have one thing I want to confirm. Is this new feature meant for top-level imports only? I noticed:

```diff
--- original/foo.py
+++ fixed/foo.py
@@ -1,3 +1,4 @@
 def z():
-    from ctypes import c_short, c_uint, c_int, c_long, pointer, POINTER, byref
+    from ctypes import POINTER
+    from ctypes import byref
     POINTER, byref
```

It seems to use the old behavior for indented cases. This is fine if intended. But I just wanted to check.

Thanks

**Comment by adhikasp** [comment]
Oh no, I did not mean that. The behaviour of top-level import and inside function should be same right?

I made change to support non-top level import and the related test.

**Comment by myint** [comment]
Thanks for sticking with this! I'm running fuzz tests against this right now. Once it runs okay for a few more hours, I'll merge it.

**Comment by myint** [comment]
Interesting! Somehow I committed to your repository. I was intending to continue committing to my [branch](https://github.com/myint/autoflake/commits/no-split-from-import). But instead, my latest commits ended up in your repository's [branch of the same name](https://github.com/adhikasp/autoflake/tree/no-split-from-import). Maybe GitHub grants permission to the repository owner to modify pull request branches from the forked repository.

**Pull request merged**
