### PR TITLE
More comprehensive star-import fixer thing.

### PR DESCRIPTION
**Pull request by fake-name**
Basically the title. 

This basically implements https://github.com/myint/autoflake/issues/30

### CODE REVIEW

**Comment by fake-name** [comment]
It's implemented as a separate tool because I can't really be confident it'll fix everything properly, in every case. 

Right now, this new tool successfully fixed the files I'm reworking, but that's not a broader guarantee. Particularly, really complex metaprogramming stuff will (probably* either get broken, or missed.

OTOH, it will probably get people 90+% of the way towards removing any garbage star imports.

**Comment by myint** [comment]
So is this trying to handle the case where there are multiple star imports? Currently for simplicity, `--expand-star-imports` ignores cases where there are:

- Multiple star imports
- `__all__` in the code
- `del` in the file.

**Comment by fake-name** [comment]
@myint - Correct.

This handles arbitrary cases with star imports.

All star imports are replaced with flat imports:

````
from os.path import *
```

Is converted to 

```
import os.path
```

The star-imported libraries are scanned for exported symbols.

All functions and variables are examined. Any names which are assigned to are masked off. Function calls and constants used in the rhs of an assignment are checked to see if they exist in the star-imported libraries, and if so, the relevant use is updated to use the full `os.path.xxx` or similar name.

**Comment by myint** [comment]
Ah, it flattens it. Interesting!

**Comment by fake-name** [comment]
Yeah, basically my use-case is I'm trying to add some stuff to https://github.com/LinuxCNC/linuxcnc/blob/master/src/emc/usr_intf/axis/scripts/axis.py, which is probably the worst python source I've ever interacted with.

It star-imports multiple packages, and it basically impossible to follow. This tool successfully fully canonizes all the function calls without any negative effects.

**Comment by Alok** [comment]
Any updates on this? For a lot of scientific python code, this would be perfect because they're *full* of star imports thanks to an overstuffed `utils.py` file, but I've never seen one that uses any fancy runtime binding that could break this tool.

**Comment by fake-name** [comment]
@Alok - Check out [the file](https://github.com/fake-name/autoflake/blob/master/autostar.py), point it at your code, and see what it does. Worst case, you'll have to revert.

In my limited use, it seemed to do what I needed, though it has issues with not being sure the correct library path things should be imported from sometimes.

Basically:
```  
library_1
 (contains *thing*)

   +    +
   |    |
   |    +>library_2
   |     (from library_1 import thing
   |        +
   |        |
   v        v
Target script
from library_1 import *
from library_2 import *

```

Since the tool sees "thing" in both library_1 and library_2, it may replace
references to "thing" with "library_2.thing". This will function, though it 
can be confusing.

Either way, it's something of an improvement.

**Comment by graingert** [comment]
it may be better to use https://github.com/davidhalter/jedi

**Comment by fake-name** [comment]
@graingert - If that doesn't *rewrite your code to fix thing*, it's not meaningfully similar.

**Comment by graingert** [comment]
I know but you can use it to determine the available imports

**Comment by fake-name** [comment]
Yeah, but the whole point of this project, as far as I'm aware, *is to fix things automatically*.

**Comment by graingert** [comment]
Yes I was suggesting you use Jedi here as a library

**Comment by fake-name** [comment]
Needed to use this again. It turns out it can be dumb and override loop variables that are the same name as an imported package (why would you *do* that).

```
from thing.thing_2 import lvar

<code>

for lvar in range(1,10):
    <code>
```
got turned into 
```
import thing.thing_2

<code>

for thing.thing_2.lvar in range(1,10):
    <code>
```

Which is actually kind of funny, really (it can wind up causing some bizarre issues by clobbering symbols in an imported module). 

Other then that, it continues to be damn handy, and realistically masking imported modules with local variable names is so terrible a practice that I kind of think anyone who did that deserves the weird bugs.

**Comment by fake-name** [comment]
More patches for multiple subscript operators. Also I created https://github.com/fake-name/PyDeStar so I'm closing this.

**Pull request closed without merging**
